name: My-GitHub-Actions

on:
  push:
    branches:
    - master
jobs:
  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: print hello message11
      run: echo "Hello World"
    - name: print hello message12
      run: echo "Hello World"

  my_deploy2:
    runs-on: ubuntu-latest
    steps:
    - name: print hello message21
      run: echo "Hello World"
    - name: print hello message22
      run: echo "Hello World"
      
